# Generated by Django 2.1.3 on 2018-11-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='account',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transfer',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
