# Generated by Django 2.1.3 on 2018-12-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksite', '0003_auto_20181211_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='confirmed',
            field=models.BooleanField(),
        ),
    ]
