var child = [
  { 'dupe': false, 'type': 4, 'name': 'about', 'dir': 'c0', 'linked': 2, 'url': 'http://127.0.0.1:8000/about/', 'fetched': true, 'code': 200, 'len': 2532, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 2, 0, 4, 0 ], 'sig': 0x5d5f5527 },
  { 'dupe': false, 'type': 4, 'name': 'admin', 'dir': 'c1', 'linked': 5, 'url': 'http://127.0.0.1:8000/admin/', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': true, 'child_cnt': 5, 'issue_cnt': [ 3, 8, 0, 0, 0 ], 'sig': 0xfdf13307 },
  { 'dupe': false, 'type': 4, 'name': 'logout', 'dir': 'c2', 'linked': 0, 'url': 'http://127.0.0.1:8000/logout/', 'fetched': true, 'code': 200, 'len': 2687, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 2, 0, 4, 0 ], 'sig': 0x649126a7 },
  { 'dupe': false, 'type': 4, 'name': 'password', 'dir': 'c3', 'linked': 0, 'url': 'http://127.0.0.1:8000/password/', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 2, 0, 0, 0 ], 'sig': 0xa52f99df },
  { 'dupe': false, 'type': 4, 'name': 'password-reset', 'dir': 'c4', 'linked': 5, 'url': 'http://127.0.0.1:8000/password-reset/', 'fetched': true, 'code': 200, 'len': 3277, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': true, 'child_cnt': 3, 'issue_cnt': [ 0, 6, 1, 8, 0 ], 'sig': 0xa4bb1ecd },
  { 'dupe': false, 'type': 4, 'name': 'register', 'dir': 'c5', 'linked': 5, 'url': 'http://127.0.0.1:8000/register/', 'fetched': true, 'code': 200, 'len': 5001, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 5, 'issue_cnt': [ 1, 7, 0, 4, 0 ], 'sig': 0x24c46f51 },
  { 'dupe': false, 'type': 4, 'name': 'static', 'dir': 'c6', 'linked': 2, 'url': 'http://127.0.0.1:8000/static/', 'fetched': true, 'code': 404, 'len': 1634, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 10, 'issue_cnt': [ 21, 12, 0, 0, 0 ], 'sig': 0xe4e0cf58 },
  { 'dupe': false, 'type': 4, 'name': 'usr', 'dir': 'c7', 'linked': 1, 'url': 'http://127.0.0.1:8000/usr/', 'fetched': true, 'code': 404, 'len': 4536, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': '[none]', 'missing': true, 'csens': false, 'child_cnt': 10, 'issue_cnt': [ 0, 10, 0, 0, 0 ], 'sig': 0xef75907b },
  { 'dupe': false, 'type': 16, 'name': 'login', 'dir': 'c8', 'linked': 5, 'url': 'http://127.0.0.1:8000/login', 'fetched': true, 'code': 200, 'len': 3911, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 4, 'issue_cnt': [ 8, 6, 0, 7, 0 ], 'sig': 0x3f9d595f },
  { 'dupe': false, 'type': 32, 'name': 'summary', 'dir': 'c9', 'linked': 2, 'url': 'http://127.0.0.1:8000/summary', 'fetched': true, 'code': 301, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 2, 0, 0, 0 ], 'sig': 0xc413dfef }
];
